using System;
using System.Linq;
using System.Collections.Generic;

namespace ProjectEuler
{
	/// <summary>
	/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	/// </summary>
	public class Problem2
	{
		public Problem2()
		{
		}

		public List<int> FibonaccisUpTo(int max)
		{
			var fibonaccis = new List<int>();
			var last = 0;
			var current = 1;
			for (int i = 1; i < max; i=last + current)
			{
				fibonaccis.Add(i);
				last=current;
				current = i;
			}
			
			return fibonaccis;
		}
		
		public int FibonacciEvensSum(int max)
		{
			var sum = 0;
			var last = 0;
			var current = 1;
			for (int i = 1; i < max; i=last + current)
			{
				if (i%2 == 0) sum += i;
				last=current;
				current = i;
			}
			return sum;
		}
	}
}

