using System;
using System.Linq;
using System.Collections.Generic;
using NSpec;

namespace ProjectEuler
{
	/// <summary>
	/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	/// </summary>
	public class describe_Problem2 : nspec
	{
		void Sum_of_fibonacci_numbers_to_10()
		{
			var numbers = FibonaccisUpTo(10);
			it["count of naturals should be 5"] = () => numbers.Count.should_be(5);
			it["the list should contain 1"] = () => numbers.should_contain(1);
			it["the list should contain 2"] = () => numbers.should_contain(2);
			it["the list should contain 3"] = () => numbers.should_contain(3);
			it["the list should contain 5"] = () => numbers.should_contain(5);
			it["the list should contain 8"] = () => numbers.should_contain(8);
			it["the sum of fibonacci evens under 10 should be 10"] = () => FibonacciEvensSum(10).should_be(10);
		}
		
		void Sum_of_fibonacci_numbers_to_4_million()
		{
			it["the sum of fibonacci evens under 4,000,000 should be 4613732"] = () => FibonacciEvensSum(4000000).should_be(4613732);
		}

		public List<int> FibonaccisUpTo(int max)
		{
			var fibonaccis = new List<int>();
			var last = 0;
			var current = 1;
			for (int i = 1; i < max; i=last + current)
			{
				fibonaccis.Add(i);
				last=current;
				current = i;
			}
			
			return fibonaccis;
		}
		
		public int FibonacciEvensSum(int max)
		{
			var sum = 0;
			var last = 0;
			var current = 1;
			for (int i = 1; i < max; i=last + current)
			{
				if (i%2 == 0) sum += i;
				last=current;
				current = i;
			}
			return sum;
		}
	}
}

